### ISSUE TITLE
Should we add <ORDER-TREE? REVERSE-DEFINED>? Not so fast...

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1-invclues#5]
At some point in late 1985, it appears the behavior of ZILCH changed in how it generates the object tree. ZILF, by default, emulates the older behavior. Usually the object trees aren't identical, but the children of an object are generally ordered the same way as in the original release.

In practical terms, Ballyhoo and all subsequent games use a different tree ordering, and this can potentially cause problems when compiling the game with ZILF. For most games the solution seems pretty clear: Add ```<ORDER-TREE? REVERSE-DEFINED>```.

But here we have a game that was originally release with one tree ordering, and then later re-released with a different tree ordering. So should we try to emulate the Solid Gold release, or should we assume that the original release is closer to the author's original intention?

As an example, here's what the kitchen looks like in the original release, and in the Solid Gold release when compiled with ZILF:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table seems to have been used
recently for the preparation of food. A passage leads to the west and a dark
staircase can be seen leading upward. A dark chimney leads down and to the east
is a small window which is open.
On the table is an elongated brown sack, smelling of hot peppers.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
```

Here's what it looks like in the official Solid Gold release, and in one compiled with ZILF and ```<ORDER-TREE? REVERSE-DEFINED>```:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table seems to have been used
recently for the preparation of food. A passage leads to the west and a dark
staircase can be seen leading upward. A dark chimney leads down and to the east
is a small window which is open.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
On the table is an elongated brown sack, smelling of hot peppers.
```

Which of the two should we try to emulate?

**Comment by AlexProudfoot** [comment]
I think the original release output is better.

**Comment by AlexProudfoot** [comment]
No change required.

**Comment by AlexProudfoot** [comment]
I don't think the change in object order was deliberate. I can't prove it for a fact but, since there is no documentation to the contrary, I'm going to assume it's an unintended consequence of a change in ZILCH. No action required.
